Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.10"
  config.disksize.size = "50GB"
  config.vm.synced_folder "../", "/home/workspace"
  config.vm.network "private_network", ip: "172.30.1.5"


  config.vm.provider "virtualbox" do |v|
    v.memory = 12000
    v.cpus = 4
  end

  config.vm.provision "shell", path: "build/installers/prerequisites.sh", privileged: true
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "build/ansible-playbook.yml"
    ansible.verbose = "vvv"
  end

  # Expose Ports
  config.vm.network "forwarded_port", guest: 8888, host: 8888  # SOS Notebook

  # Custom Configs
  $workdir = <<-SCRIPT
    #/bin/bash
    # Set Workdir
    if ! grep -q "cd /vagrant" ~/.bashrc ; then
      echo "cd /home/workspace" >> /home/vagrant/.bashrc
    fi
  SCRIPT
  config.vm.provision "shell", inline: $workdir, privileged: false

end
